spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: Fiap-Registra_Veiculo
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: prod