spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:registra_veiculo_db
    username: postgres
    password: XXXI.X.MMXVII
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          url: jdbc:postgresql://postgresql:5432/registra_veiculo_db
    active: dev
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
        hibernate:
          SQL: DEBUG
          type: TRACE
  sql:
    init:
      mode: always
name: Archive test results
uses: actions/upload-artifact@v3
with:
  name: surefire-reports
  path: target/surefire-reports
